CREATE TABLE IF NOT EXISTS url_id
(id INT AUTO_INCREMENT NOT NULL,
url VARCHAR(255) NOT NULL,
url_id VARCHAR(255) NOT NULL,
PRIMARY KEY(id))
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
