version: '2.1'
services:

  db:
    image: mysql:5.7
    container_name: db_container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urldb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    links:
      - db:db
    ports:
      - 8088:80

  core-app:
    build:
      context: ./.docker/php
    container_name: core-app
    working_dir: /var/app
    volumes:
      - ./app:/var/app
      - ${HOME}/.ssh:/root/.ssh:ro
    depends_on:
      - db

  core-server:
    container_name: core-server
    image: 'nginx:1.19'
    volumes:
      - './app:/var/app:ro'
      - './.docker/nginx/conf.d:/etc/nginx/conf.d:ro'
    ports:
      - 8060:80
    depends_on:
      - core-app
